# Generated by Django 5.2.15 on 2026-06-06 12:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('notes', models.TextField(blank=True)),
                ('expected_redaction_salt_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_prefix', models.CharField(max_length=16, unique=True)),
                ('token_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'token_prefix'],
            },
        ),
        migrations.CreateModel(
            name='DumpUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_sha256', models.CharField(max_length=64)),
                ('raw_text', models.TextField()),
                ('raw_json', models.JSONField()),
                ('schema_version', models.CharField(max_length=80)),
                ('mode', models.CharField(choices=[('public', 'Public'), ('sensitive', 'Sensitive')], max_length=16)),
                ('redaction_salt_id', models.CharField(blank=True, max_length=128)),
                ('exported_at_ms', models.PositiveBigIntegerField()),
                ('producer_name', models.CharField(max_length=120)),
                ('producer_version', models.CharField(max_length=80)),
                ('account_ref', models.CharField(max_length=256)),
                ('account_id', models.CharField(max_length=256)),
                ('group_id', models.CharField(max_length=256)),
                ('epoch', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('member_count', models.PositiveIntegerField()),
                ('required_app_components', models.JSONField(blank=True, default=list)),
                ('admins', models.JSONField(blank=True, default=list)),
                ('relays', models.JSONField(blank=True, default=list)),
                ('nostr_group_id', models.CharField(blank=True, max_length=256)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forensic_uploads', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='forensics.incident')),
                ('upload_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='forensics.uploadtoken')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForensicsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='forensics.dumpupload')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='forensics.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForensicsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=256)),
                ('group_id', models.CharField(max_length=256)),
                ('epoch', models.PositiveBigIntegerField()),
                ('state', models.CharField(max_length=80)),
                ('payload_kind', models.CharField(max_length=120)),
                ('envelope_kind', models.CharField(max_length=120)),
                ('timestamp', models.PositiveBigIntegerField()),
                ('payload_len', models.PositiveBigIntegerField()),
                ('payload_digest', models.CharField(max_length=256)),
                ('has_payload_hex', models.BooleanField(default=False)),
                ('openmls_content_kind', models.CharField(blank=True, max_length=120)),
                ('openmls_source_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('openmls_message_digest', models.CharField(blank=True, max_length=256)),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forensics.dumpupload')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
                'indexes': [models.Index(fields=['group_id', 'epoch'], name='forensics_f_group_i_2d91ca_idx'), models.Index(fields=['openmls_content_kind', 'openmls_source_epoch'], name='forensics_f_openmls_7e19a5_idx'), models.Index(fields=['payload_digest'], name='forensics_f_payload_cbc955_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dumpupload',
            index=models.Index(fields=['group_id', 'epoch'], name='forensics_d_group_i_470471_idx'),
        ),
        migrations.AddIndex(
            model_name='dumpupload',
            index=models.Index(fields=['account_id'], name='forensics_d_account_520a58_idx'),
        ),
        migrations.AddIndex(
            model_name='dumpupload',
            index=models.Index(fields=['created_at'], name='forensics_d_created_9599a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='dumpupload',
            constraint=models.UniqueConstraint(fields=('incident', 'raw_sha256'), name='unique_dump_upload_per_incident_sha256'),
        ),
    ]
