# Generated by Django 5.2.15 on 2026-06-06 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('group_ref', models.CharField(blank=True, db_index=True, max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_prefix', models.CharField(max_length=16, unique=True)),
                ('token_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'token_prefix'],
            },
        ),
        migrations.CreateModel(
            name='AuditFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('raw_text', models.TextField()),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], default='valid', max_length=16)),
                ('validation_error', models.TextField(blank=True)),
                ('total_line_count', models.PositiveIntegerField(default=0)),
                ('valid_event_count', models.PositiveIntegerField(default=0)),
                ('invalid_event_count', models.PositiveIntegerField(default=0)),
                ('duplicate_event_count', models.PositiveIntegerField(default=0)),
                ('first_line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('last_line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seq', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_seq', models.PositiveBigIntegerField(blank=True, null=True)),
                ('first_wall_time_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_wall_time_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('engine_ids', models.JSONField(blank=True, default=list)),
                ('schema_versions', models.JSONField(blank=True, default=list)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_uploads', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_files', to='forensics.auditgroup')),
                ('upload_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_files', to='forensics.uploadtoken')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='forensics.auditgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('line_hash', models.CharField(max_length=64)),
                ('raw_line', models.TextField()),
                ('raw_event', models.JSONField(blank=True, null=True)),
                ('raw_kind', models.JSONField(blank=True, default=dict)),
                ('parse_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], default='valid', max_length=16)),
                ('validation_error', models.TextField(blank=True)),
                ('schema_version', models.CharField(blank=True, max_length=80)),
                ('seq', models.PositiveBigIntegerField(blank=True, null=True)),
                ('wall_time_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('engine_id', models.CharField(blank=True, max_length=64)),
                ('group_ref', models.TextField(blank=True)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('msg_id', models.TextField(blank=True)),
                ('outbound_msg_id', models.TextField(blank=True)),
                ('outbound_welcome_msg_ids', models.JSONField(blank=True, default=list)),
                ('epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('from_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('to_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pending_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('restored_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('current_tip_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('selected_fork_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('selected_tip_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload_len', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload_digest', models.CharField(blank=True, max_length=128)),
                ('candidate_digest', models.CharField(blank=True, max_length=128)),
                ('incumbent_digest', models.CharField(blank=True, max_length=128)),
                ('envelope_kind', models.CharField(blank=True, max_length=120)),
                ('outcome', models.CharField(blank=True, max_length=120)),
                ('outcome_kind', models.CharField(blank=True, max_length=120)),
                ('stale_reason', models.CharField(blank=True, max_length=160)),
                ('decision', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('winner', models.CharField(blank=True, max_length=120)),
                ('new_state', models.CharField(blank=True, max_length=120)),
                ('pending_kind', models.CharField(blank=True, max_length=120)),
                ('intent_kind', models.CharField(blank=True, max_length=120)),
                ('result_kind', models.CharField(blank=True, max_length=120)),
                ('proposal_kind', models.CharField(blank=True, max_length=120)),
                ('snapshot_name', models.CharField(blank=True, max_length=256)),
                ('selected_branch_id', models.CharField(blank=True, max_length=256)),
                ('detail', models.TextField(blank=True)),
                ('fallback_snapshot_used', models.BooleanField(blank=True, null=True)),
                ('invalidated_msg_id', models.TextField(blank=True)),
                ('max_rewind_commits', models.PositiveBigIntegerField(blank=True, null=True)),
                ('candidate_count', models.PositiveIntegerField(blank=True, null=True)),
                ('eligible_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='forensics.auditfile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='forensics.auditgroup')),
            ],
            options={
                'ordering': ['wall_time_ms', 'engine_id', 'line_number', 'id'],
                'indexes': [models.Index(fields=['engine_id', 'wall_time_ms'], name='forensics_a_engine__dc8e0b_idx'), models.Index(fields=['group_ref', 'wall_time_ms'], name='forensics_a_group_r_742f7c_idx'), models.Index(fields=['msg_id'], name='forensics_a_msg_id_c2095a_idx'), models.Index(fields=['event_type'], name='forensics_a_event_t_e472fe_idx'), models.Index(fields=['source_epoch'], name='forensics_a_source__798175_idx'), models.Index(fields=['payload_digest'], name='forensics_a_payload_099953_idx'), models.Index(fields=['candidate_digest'], name='forensics_a_candida_1970fa_idx'), models.Index(fields=['parse_status'], name='forensics_a_parse_s_c18ec7_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'line_hash'), name='unique_audit_event_line_hash_per_group')],
            },
        ),
        migrations.AddIndex(
            model_name='auditfile',
            index=models.Index(fields=['validation_status'], name='forensics_a_validat_afee87_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfile',
            index=models.Index(fields=['created_at'], name='forensics_a_created_e39b7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditfile',
            constraint=models.UniqueConstraint(fields=('group', 'file_sha256'), name='unique_audit_file_per_group_sha256'),
        ),
    ]
