# Generated by Django 5.2.15 on 2026-06-08 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditevent',
            name='unique_audit_event_line_hash_per_group',
        ),
        migrations.RemoveConstraint(
            model_name='auditfile',
            name='unique_audit_file_per_group_sha256',
        ),
        migrations.RemoveField(
            model_name='auditfile',
            name='group',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='account_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='account_refs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='group_refs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='forensics.auditgroup'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['account_ref', 'engine_id'], name='forensics_a_account_c78c35_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.UniqueConstraint(fields=('audit_file', 'line_number'), name='unique_audit_event_line_per_file'),
        ),
        migrations.AddConstraint(
            model_name='auditfile',
            constraint=models.UniqueConstraint(fields=('file_sha256',), name='unique_audit_file_sha256'),
        ),
    ]
