# Generated by Django 5.2.15 on 2026-06-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0002_remove_auditevent_unique_audit_event_line_hash_per_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfile',
            name='source_account_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='source_app_version',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='source_device_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='source_platform',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
