# Generated by Django 6.0.6 on 2026-06-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0003_auditfile_source_account_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='accepted_relay_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='context_engine',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='context_group',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='context_human_action',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='context_operation_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='context_transport',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='failed_relays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='human_action_action',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='human_action_component_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='human_action_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='human_action_message_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='human_action_origin',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='human_action_phase',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='human_action_target_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='met_required_acks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='raw_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='relay_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='required_acks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='target_kind',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['human_action_action'], name='forensics_a_human_a_97f97e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['context_operation_id'], name='forensics_a_context_eb4dfd_idx'),
        ),
    ]
